// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomManipulation_Microservice.Domain;

namespace RoomManipulation_Microservice.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.EquipmentStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long?>("EquipmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RoomId");

                    b.ToTable("EquipmentStatistic");
                });

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.Renovation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RenovationStatus")
                        .HasColumnType("int");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Renovation");
                });

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentNumberOfPatients")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumberOfPatientsForHospitalization")
                        .HasColumnType("int");

                    b.Property<string>("RoomCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("RoomTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.RoomType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.EquipmentStatistic", b =>
                {
                    b.HasOne("RoomManipulation_Microservice.Domain.Model.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.HasOne("RoomManipulation_Microservice.Domain.Model.Room", null)
                        .WithMany("EquipmentStatistic")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.Renovation", b =>
                {
                    b.HasOne("RoomManipulation_Microservice.Domain.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.OwnsOne("RoomManipulation_Microservice.Domain.Model.Period", "Period", b1 =>
                        {
                            b1.Property<long>("RenovationId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("RenovationId");

                            b1.ToTable("Renovation");

                            b1.WithOwner()
                                .HasForeignKey("RenovationId");
                        });
                });

            modelBuilder.Entity("RoomManipulation_Microservice.Domain.Model.Room", b =>
                {
                    b.HasOne("RoomManipulation_Microservice.Domain.Model.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
