services:
 
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: newmydb
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    image: daviddrvar/webapp:latest
    container_name: webapp
    restart : always
    environment: 
      - server_address= http://servers:51393
    networks:
      - demo
    ports: 
      - 49153:49153
    depends_on:
      - servers

  servers:
    build: .
    image: daviddrvar/interlayer:latest
    container_name: interlayer
    restart : always
    networks:
      - demo
    ports:
      - 51393:51393
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: newmydb
      DATABASE_USERNAME_EVENTS: root
      DATABASE_PASSWORD_EVENTS: root
      DATABASE_HOST_EVENTS: mysql
      DATABASE_SCHEMA_EVENTS: eventlogs
    depends_on: 
      - mysql

volumes:
  mysql-data:

networks:
  demo:
    name: demo
    driver: bridge
    external: true