services:
 
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: newmydb
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    image: jovanjelicki/webapp:3
    container_name: webapp
    restart : always
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: newmydb
    ports: 
      - 49153:49153
    depends_on:
      - servers

  servers:
    build: .
    image: jovanjelicki/interlayer:2
    container_name: interlayer
    restart : always
    networks:
      - demo
    ports:
      - 51393:51393
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: newmydb
    depends_on: 
      - mysql

volumes:
  mysql-data:

networks:
  demo:
    name: demo
    driver: bridge